### ISSUE TITLE
issue for installing the package

### ISSUE THREAD

**Issue by CLambert1** [TheoMichelot/localGibbs#1]
Hi, 
I would like to install this package to tri simulating individual tracks from RSF, but unfortunately, I cannot install it. I tried with devtools, remotes and also directly from the source .tar in two different machines, but in all cases I get a "non-zero exist status" (no matter whether I skip the packages updating or not). There is extensive information written in the console when installing, but I am not able to decipher it and maybe get a better idea as to what's happening:
[Console_LocalGibbs.txt](https://github.com/TheoMichelot/localGibbs/files/8198897/Console_LocalGibbs.txt)
Would you have any idea? 
Thank you very much, 
Charlotte

**Comment by TheoMichelot** [comment]
Hi Charlotte,

Is your OS Windows? The package is based on some C++ code, and I think that whether compilation is successful can depend on OS and whether the dependencies are installed by default.

Could you try installing the package from the build accessible at this link: [localGibbs_0.1.0.tar.gz](https://github.com/TheoMichelot/localGibbs/releases/download/v0.1.0/localGibbs_0.1.0.tar.gz). You will need something like:
``` R
install.packages("localGibbs_0.1.0.tar.gz", repos = NULL, type = "source")
```

Théo

**Comment by CLambert1** [comment]
Hi Théo,
Thank you for the answer. I tried with the build, but the issue is still the same. I work from a Win10 computer, but also tried from a Win7 machine with the same output. What are the dependencies required? 
Charlotte

**Comment by TheoMichelot** [comment]
I think some relevant context is described in [this StackOverflow thread](https://stackoverflow.com/questions/34186508/making-an-r-package-using-rcpparmadillo-in-rstudio-meets-error-undefined-refere). I have added a Makevars.win file following advice from that thread, could you please try installing from Github again?

**Comment by CLambert1** [comment]
And... it works!!
Thank you !

**Comment by TheoMichelot** [comment]
Thanks for letting me know, glad that solved the issue!
